version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      target-branch: "develop"
      groups:
          security-updates:
              applies-to: security-updates
              patterns:
                  - "*"
