import "./globals.css";

import type { Metadata, Viewport } from "next";

// Metadata
// TODO: Rellenar el metadata
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	alternates: {
		canonical: "/",
	},
	category: "",
	robots: {
		index: false,
		follow: false,
		nocache: false,
	},
};

// Configuración de la vista
export const viewport: Viewport = {
	colorScheme: "light",
};

// Fuente(s)
import { Poppins } from "next/font/google";
const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

// Layout
export default function Root_Layout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="es-CO">
			<body className={`${poppins.className} antialiased`}>
				<main className="flex min-h-screen max-w-full">
					<div className="w-full grow">{children}</div>
				</main>
			</body>
		</html>
	);
}
